# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'catstagram_ios' do
  # Comment the next line if you don't want to use dynamic frameworks use_frameworks!
  pod 'Alamofire', '~>5.5'

  # Pods for catstagram_ios
  pod 'Kingfisher', '~> 7.0'
  
  # Pod SnapKit
  pod 'SnapKit', '~> 5.6.0'

  target 'catstagram_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'catstagram_iosUITests' do
    # Pods for testing
  end

end
